#!/usr/bin/env php
<?php

/*
 * This file is part of PHP CS Fixer.
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

define('LINK_MONITOR_PATH', __DIR__);

date_default_timezone_set('Asia/Shanghai');
require LINK_MONITOR_PATH . '/vendor/autoload.php';
$config = require_once LINK_MONITOR_PATH . '/config/config.php';

$main = new LinkMonitor\Monitor\Main($config);
$main->start();